[package]
name = "imgsim"
version = "0.1.0"
edition = "2021"
authors = ["Max Gilmour"]
description = "A tool that finds similar images through various methods."
readme = "README.md"
repository = "https://github.com/maxgmr/imgsim"
license = "GPL-3.0-or-later"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.4", features = ["cargo"] }
serde = { version = "1.0.201", features = ["derive"]}
toml = "0.8.12"

[dev-dependencies]
pretty_assertions = "1.4.0"