[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.clean]
command = "cargo"
args = ["clean", "--release"]

[tasks.createconfig]
command = "echo"
args = ["test"]

[tasks.install]
dependencies = ["clean", "build", "createconfig"]