[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.clean]
command = "cargo"
args = ["clean", "--release"]

[tasks.createconfig]
script = '''
sudo mkdir -p ~/.config/imgsim/
sudo cp -n ./config/config.toml ~/.config/imgsim/config.toml
sudo chmod 666 ~/.config/imgsim/config.toml
sudo cp ./config/config.toml ~/.config/imgsim/default-config.toml
'''

[tasks.addtousr]
script = '''
sudo mkdir -p /usr/local/bin/ 
sudo cp ./target/release/imgsim /usr/local/bin/imgsim
'''

[tasks.install]
dependencies = ["clean", "build", "createconfig", "addtousr"]

[tasks.uninstall]
script = '''
sudo rm -rf ~/.config/imgsim/
sudo rm -f /usr/local/bin/imgsim
'''