[args]
input_dir = ""                  # default = ""; this defaults to the current working directory. Change with caution as paths are OS-dependent. Better to specify in cli args.
pixeldist_alg = "Euclidean"     # default = "euclidean"
clustering_alg = "Agglomerative"# default = "kmeans"
similarity_alg = "ColourSim"    # default = "coloursim"

[settings]
debug = true                    # default = false
verbose = false                 # default = false; doesn't matter because it will be overwritten by cli flag
max_width = 1000                # default = 1000; in pixels. anything wider than this will be shrunk.
max_height = 1000               # default = 1000; in pixels. anything taller than this will be shrunk.

[agglomerative_options]
tolerance = 0.6                 # default = 0.5; distance between pixels must be above this percentile to remain as separate groups

[coloursim_options]
cluster_cutoff = 0.1            # default = 0.1; any clusters which make up less than (cluster_cutoff * 100)% of the image will not be considered.