[args]
# The default directory in which imgsim searches for images to compare. Leave this blank to default to the current working directory.
input_dir = ""
# The algorithm used to calculate the colour distance/difference between pixels.
pixeldist_alg = "Euclidean"
# The algorithm used to group the pixels together into clusters.
clustering_alg = "Agglomerative"
# The algorithm used to calculate the similarity of images.
similarity_alg = "Clustersize"

[settings]
# Toggling this on shows more detailed console messages.
debug = false
# Any images wider than this width will be shrunk down to a max_width * max_height size for calculations. Does not affect original image.
max_width = 1000
# Any images taller than this height will be shrunk down to a max_width * max_height size for calculations. Does not affect original image.
max_height = 1000

[agglomerative_options]
# Adjacent pixels with a distance larger than (tolerance * 100)% of pixel distances will not be merged into a single cluster.
tolerance = 0.6

[kmeans_options]
# The maximum number of clusters to try. A higher number means slower computation time.
max_k = 10
# If the average silhouette is higher than this level, then return before reaching max_k. May speed up processing time. Set to '1.0' to never return early.
silhouette_threshold = 0.7

[coloursim_options]
# Clusters which constitute less than (coloursim_cluster_cutoff * 100)% of the image's pixels will not be considered for similarity calculation.
coloursim_cluster_cutoff = 0.1

[clustersize_options]
# Clusters which constitute less than (clustersize_cluster_cutoff * 100)% of the image's pixels will not be considered for similarity calculation.
clustersize_cluster_cutoff = 0.05