[args]
input_dir = ""                  # default = ""; this defaults to the current working directory. Change with caution as paths are OS-dependent. Better to specify in cli args.
pixeldist_alg = "Euclidean"     # default = "euclidean"
clustering_alg = "KMeans"       # default = "kmeans"
similarity_alg = "ColourSim"    # default = "coloursim"

[settings]
debug = true                    # default = false
verbose = false                 # default = false; doesn't matter because it will be overwritten by cli flag
max_width = 700                 # default = 800; in pixels. anything wider than this will be shrunk.
max_height = 700                # default = 800; in pixels. anything taller than this will be shrunk.

[agglomerative_options]
tolerance = 0.9                 # default = 0.5; distance between pixels must be above this percentile to remain as separate groups